# Builds a lightweight retrieval index over the XCSV vault and wiki.
# The output is markdown only; it intentionally skips common secret/config names.

[CmdletBinding()]
param(
    [string]$VaultDir = 'C:\Users\Architect\Desktop\ARMA3_EXILE_CODEX',
    [string]$WikiDir = 'D:\XCSV\wiki',
    [string]$OutFile = 'D:\XCSV\wiki\Memory-Index.md'
)

$ErrorActionPreference = 'Stop'

function Relative-Path([string]$Root, [string]$Path) {
    $rootUri = [Uri]((Resolve-Path -LiteralPath $Root).Path.TrimEnd('\') + '\')
    $pathUri = [Uri]((Resolve-Path -LiteralPath $Path).Path)
    [Uri]::UnescapeDataString($rootUri.MakeRelativeUri($pathUri).ToString()).Replace('/', '\')
}

function Add-NoteEntries([string]$Root, [string]$Tier, [System.Collections.Generic.List[string]]$Lines) {
    if (-not (Test-Path -LiteralPath $Root)) { return }
    $files = Get-ChildItem -LiteralPath $Root -Recurse -File -Filter '*.md' |
        Where-Object {
            $_.FullName -notmatch '\\\.obsidian\\' -and
            $_.Name -notmatch '(secret|token|password|credential|config\.json|xcsv_guard\.json)'
        } |
        Sort-Object FullName

    foreach ($file in $files) {
        $rel = Relative-Path -Root $Root -Path $file.FullName
        $headings = Get-Content -LiteralPath $file.FullName -ErrorAction SilentlyContinue |
            Select-String -Pattern '^(#{1,3})\s+(.+)$' |
            Select-Object -First 10
        if (-not $headings) {
            $Lines.Add("| $Tier | `$rel` | |")
            continue
        }
        foreach ($heading in $headings) {
            $title = $heading.Matches[0].Groups[2].Value.Replace('|', '\|')
            $Lines.Add("| $Tier | `$rel` | $title |")
        }
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Memory Index')
$lines.Add('')
$lines.Add('Generated by `D:\XCSV\tools\build-memory-index.ps1`. It is a lightweight local RAG map: trust the live server first, committed source second, vault/wiki notes third, and generated docs last.')
$lines.Add('')
$lines.Add('| tier | path | heading |')
$lines.Add('|---|---|---|')
Add-NoteEntries -Root $VaultDir -Tier 'vault' -Lines $lines
Add-NoteEntries -Root $WikiDir -Tier 'wiki' -Lines $lines

$encoding = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutFile, ($lines -join [Environment]::NewLine) + [Environment]::NewLine, $encoding)
[pscustomobject]@{ OutFile = $OutFile; Entries = [Math]::Max(0, $lines.Count - 6) }
